### ISSUE TITLE
Sprint0 Checklist

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/ngsa#1]
# Sprint0 Checklist

## Tooling
- [x] Setup/Configure Azure Subscriptions
- [x] CI-CD Tooling (CI in place - CD TBD)
- [x] Work Item tracking Tooling (GitHub) 
- [x] Collaboration and Communication Tooling  (Teams)
- [x] Share user lists for Azure AD 
- [x] Share user lists for Source Control

## Planning
- [x] Define success criteria (M1)
- [x] Customer requirements (M1)
- [x] Customer Team identified
- [x] Microsoft Team identified 
- [x] Architecture Review Process

## Execution
- [x] Sprint 0 plan (all stories and all features)
- [X] Sprint Plan (2 week sprints per customer; Estimating 6 weeks/3 sprints)
- [x] Onsite plan (N/A)
- [x] Repo Policies (Main, 1 approver, Team access) 
- [x] Branch Management (1 approver, SLA 12hrs)
- [x] Scrum ceremonies scheduled (Standups:  M,T,W, Thur; @ 4;30pm; Retro: Every other Wednesday, Sprint: 2 weeks )

## Next Steps
- [x]  Create doc folder 
- [x]  Standup, Review/Retro, Planning meetings sent
- [x]  Update templates
- [x]  Update tags
- [x]  Define Epics in repo
- [x]  Update Working Agreement (document)
