### ISSUE TITLE
Configure CD to Pre-prod Environment

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/ngsa#103]
## Description

What: 

We currently have the CI pipeline working and creating images.  We need to add the deployment mechanism to the workflow.
 
Why:
- So that we may have a perpetually running and tested pre-production deployment to help ensure high-quality deliverables.

When:
- Every time a PR is successfully merged for code changes to the app.

Where:
 - Deploy to pre-prod

## Tasks
- [x] Design Review #209
- [x] Modify current CI to support semver tags #210
- [x] Create ngsa-cd repo and migrate helm chart #211
- [x] Install fluxcd operator in all clusters #212 
- [x] Document setup of fluxcd installation + helm operator #213

## Acceptance Criteria

- deploys latest image to pre-prod AKS environment
- checks deployment for validity
- rolls back deployment if failed

## Constraints
- N/A 

## References:
- References #11 
- Predecessor #43
