### ISSUE TITLE
Implement Fluent Bit Log Collector 

### ISSUE THREAD

**Issue by jofultz** [retaildevcrews/ngsa#123]
## Description

What: 
 
Design and implement Fluent Bit for log collection in-place of current sidecar implementation.
 
Why:
- Feedback from SAs
- More aligned with industry norms

When:
- As part of app deployments

Where:
 - All deployments

## Tasks
- [x] Spike and Design Review Fluent Bit implementation 
- [x] Remove Sidecar #141
- [x] Bring in a private version of webv #142
- [x] Implement and validate  #135 
- [x] Design reviews: #132, #133, #134, #138
- [x] bare metal setup
- [x] AKS setup #137 

## Acceptance Criteria

- Should log data to Log Analytics Instance
- Should determine LA target for the environment via configuration
- Should provide requisite log data to support dashboard metrics

## Constraints
- N/A 

## References:
- References #12
