### ISSUE TITLE
Engineering Fundamentals Process

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/ngsa#149]
## Description

What: 
 - checklists and pre-work documentation
 
Why:
- to follow CSE recommended engineering fundamentals

When:
- monthly

Where:
 - github, ado, and snowball

## Tasks
- [X] Game Plan Document
- [X] Game Plan Review
- [x] CPRs
- [x] Tech Led Engineering Checklist
- [x] Engineering Surveys

## Acceptance Criteria

- Game Plan review completed & plan uploaded
- CPR pre-work completed and uploaded 24hrs in advance
-  Artifacts created and uploaded into ADO

## Constraints
- N/A
