### ISSUE TITLE
Scrum

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/ngsa#150]
## Description

What: 
 - daily standups, retros, and reviews, 
 
Why:
- following scrum practices

When:
- end of a sprint and daily

Where:
 - Team channel

## Tasks
- [x] Schedule daily standups
- [x] Schedule Retros for end of sprint
- [x] Create Retro board & issues
 
## Acceptance Criteria

- Meetings are scheduled
- Retro boards are created

## Constraints
- N/A
