### ISSUE TITLE
Docker 101 webcast

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/ngsa#152]
## Description

What: 
 - Webcast for upskilling on Docker 
 
Why:
- establish base docker skills across team

When:
- recorded, on demand

Where:
 - NGSA Teams channel

## Tasks
- [x] Update existing documentation as needed #158
- [x] Schedule & record webcast #157
- [x] publish and share (12/1) #157

## Acceptance Criteria
- Content is available on demand
- Content is posted for broader team consumption

## Constraints
- N/A 

## References:
- References #148
