### ISSUE TITLE
Need to define CPU and RAM minimums in our YAML.

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/ngsa#169]
## Description

What: 
 - Set CPU and RAM minimums for containers
 
Why:
- so that they have sufficient starting resources

When:
- on deployment

Where:
 - Kubernetes cluster

## Tasks
- [x] Update [Loderunner YAML](https://github.com/retaildevcrews/ngsa/blob/main/IaC/AKS/cluster/charts/loderunner/templates/deployment.yaml) #373 
- [x] Update [NGSA Cosmos Dev Cluster YAML](https://github.com/retaildevcrews/ngsa/blob/main/IaC/DevCluster/app/ngsa-cosmos/ngsa.yaml) #373 
- [x] Update [NGSA In-memory Dev Cluster YAML](https://github.com/retaildevcrews/ngsa/blob/main/IaC/DevCluster/app/in-memory.yaml) #373 
- [x] Update [LoadDemo YAMLs](https://github.com/retaildevcrews/ngsa/blob/main/IaC/LoadDemo) #373 
- [x] Update [ngsa-cd app YAML](https://github.com/retaildevcrews/ngsa-cd/blob/main/charts/ngsa/templates/deployment.yaml) #374 

## Acceptance Criteria

- Ratio 1 Core : 1 GB
- NSGA In Memory = 1GB & 1 Core (1000 millicores)
- NGSA = 1GB & 1 Core (1000 millicores)
- Loderunner =  .5GB &  .5 cores (500 millicores)

## Constraints
- N/A 

## References:
- References #8
- References #9
