### ISSUE TITLE
Rebuild Pre-prod Planning

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/ngsa#171]
# Description

What: 
 - Rebuild pre-prod environments

Note: This may require us to rethink how were naming and using DNS in order to make a graceful switch.
 
Why:
- Test documentation
- Consolidate resources

When:
- ASAP

Where:
 - Azure

## Tasks
- [x] Plan and Document Resource Movement and Creation - #183
- [x] Plan and Document Initial Naming and DNS switch - #184
- [x] Review with team

## Acceptance Criteria

Plans should include:
- Replacement cluster in each region
- Clusters use multiple Availability Zones
- Initial naming and certs for pre-switch testing
- DNS Switches so names resolve to new clusters
- Loderunner runs successfully against all instances
- Logs are flowing as expected and dashboards are updating
- Handling of interim log messages (can/do we delete or just filter them out)

## Constraints
- N/A 

## References:
- Successor #181 
- References #10

**Comment by dsturgell** [comment]
Should rebuild from scratch?  Facilitate documentation checking and resource consolidation.  The path would be to build new PRE environments then switch and deallocate the old PRE environments.

bartr - I think we should. We should time it to do either before break or in Jan. Just not today (I'm doing a demo :)

ACTION: next sprint or push to Jan; notify team before as queries tied
