### ISSUE TITLE
Capturing cluster metrics in logs

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/ngsa#172]
## Description

What: 
 - Capture cluster metrics for monitoring
 - Define methods for crawl, walk, and run scenarios
 
Why:
- So that we may monitor cluster health for various levels of k8s adoption

When:
- Ongoing

Where:
 - K8s

## Tasks
- [ ] Define solution for M1 (e.g., Azure Container Insights) - #318 
- [ ] Identify any collisions with current monitoring - #318
- [ ] Configure crawl solution for current environment and update provisioning docs/scripts
- [ ] Update documentation

## Acceptance Criteria

- Methods for cluster metrics defined
- Crawl method implemented in current pre-prod environment  
- Docs updated

## Constraints
- N/A 

## References:
- References #12

**Comment by bartr** [comment]
We will need to update fluent bit so we don't double capture the app logs
