### ISSUE TITLE
convert helium typescript to use data service

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/ngsa#173]
The C# ngsa app has been converted to abstract the data retrieval as a separate data service that is deployed as a sidecar presently.  This issue is to refactor the Typescript Helium app into a Typescript **ngsa** app so that it may use the same sidecar for data access and remove the data access from the codebase directly.

## Tasks
- [x] Add and rename the the Helium Typescript code to the NGSA repo spike folder
- [x] Refactor code to call the data service
- [x] Test locally with webv running against the data service
