### ISSUE TITLE
User Story: Investigate PnP aks-secure-baseline delta to NGSA

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/ngsa#178]
## Description

What: 
- 

Why:
-

When:
- 

Where:
 - 

## Tasks
- [ ] #461
- [ ] #318 
- [ ] #383

## Acceptance Criteria
- [ ] _add acceptance criteria_
- [ ] Resolve linter errors
- [ ] Remove to-do, dead code, & unnecessary comments
- [ ] Existing documentation is updated (readme, .md's)
- [ ] New documentation needed to support the change is created
- [ ] Validation test run if applicable

## Constraints
- N/A 

## References:
- look into this:  https://github.com/mspnp/aks-secure-baseline
- References #
