### ISSUE TITLE
IaC Bare Metal Script for Azure

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/ngsa#18]
## Description

What: 
 - Setup documentation for scripting 
 - Required Components
   - AZ 
   - Flannel networking
   - Storage mounted secrets (in memory and cosmos)
   - Istio Service Mesh
 
Why:
- To establish self managed infrastructure for application deployment

When:
- when script is run

Where:
 - Azure

## Tasks for planning
- [X] Documentation for cluster setup
~~Istio configuration as part of setup documentation~~
- [X] SSL configuration (semi-automated)
- [X] Load balancer configuration
- [X] DNS configuration (semi-automated)
- [X] Smoke/validation test 

## Acceptance Criteria

-  Parameterization
   - Naming 
   - Networking
   - Region
- Cluster configuration documented
- Smoke/Validation test passed

## References
- References #10 
- References #34

**Comment by jofultz** [comment]
Removed Istio as this isn't a go-forward configuration.  Closing as it is complete as is.
