### ISSUE TITLE
Rebuild Pre-prod Execution

### ISSUE THREAD

**Issue by jofultz** [retaildevcrews/ngsa#181]
# Description

What: 
 
This is to rebuild our environments and consolidate resources in resource groups.  This will establish new clusters and move shared resources.

Note: This may require us to rethink how were naming and using DNS in order to make a graceful switch.
 
Why:
- Test documentation
- Consolidate resources

When:
- ASAP

Where:
 - Azure

## Tasks
- [x] Build new clusters in each region in consolidated Resource Groups (https://github.com/retaildevcrews/ngsa/issues/322)
- [x] Create new DNS names for new environments (https://github.com/retaildevcrews/ngsa/issues/324)
- [x] Separate GitOps for New and Old Environments (https://github.com/retaildevcrews/ngsa/issues/335)
- [x] Update GitOps setup in current environments (https://github.com/retaildevcrews/ngsa/issues/325)
- [x] Create new log analytics instance for new environments (https://github.com/retaildevcrews/ngsa/issues/337)
- [x] Update dashboards with new variables for the new-environment (https://github.com/retaildevcrews/ngsa/issues/336)

## Acceptance Criteria

- Replacement cluster in each region
- Names resolve to new clusters
- Loderunner runs successfully against all instances
- Logs are flowing as expected and dashboards are updating

## Constraints
- N/A 

## References:
- Predecessor #171 
- References #10
