### ISSUE TITLE
Bare Metal Webcast

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/ngsa#185]
## Description

What: 
 - Webcast for upskilling on Bare Metal
 
Why:
- establish base Bare Metal  skills across team

When:
- recorded, on demand

Where:
 - NGSA Teams channel

## Tasks
- [x] Update existing documentation as needed #186 
- [x] Schedule & record webcast #187  
- [x] publish and share #187

## Acceptance Criteria
- Content is available on demand
- Content is posted for broader team consumption

## Constraints
- N/A 

## References:
- References #148
