### ISSUE TITLE
IaC Script for AKS 

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/ngsa#19]
## Description

What: 
 - Setup documentation for scripting 
 - Required Components
   - AZ 
   - Flannel networking
   - Storage mounted secrets (in memory and cosmos)
   - Istio Service Mesh
 
Why:
- To establish self managed infrastructure for application deployment

When:
- when script is run

Where:
 - Azure

## Tasks for planning
- [X] Documentation for cluster setup #54 
- [X] Istio operator yaml file #55
- [x] SSL configuration (semi-automated) #56
- [x] DNS configuration (semi-automated) #57
- [x] Smoke/validation test #58

## Acceptance Criteria

-  Parameterization
   - Multi-node configuration 
   -  Single node configuration
   -  Naming 
   -  Networking
   -  Region
-  Cluster configuration documented
-  Smoke/Validation test passed

## Constraints
- TBD

## References
- References #10
