### ISSUE TITLE
Documentation Feedback

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/ngsa#190]
## Description

What: 
- Define and implement documentation structure
- Add initial documentation 
  - Developer guidance
  - Solution Overview
  - Discrete component documentation
 
Why:
- to help users understand, navigate, and use solution

When:
- exploring or using repo

Where:
 - GitHub Repo

## Tasks
- [X] Create Epic for documentation #199 
- [x] Agree on documentation structure & document in engineering practices #200
- [x] Add overview and table of contents to root readme #201
- [x] Add a "Getting Started" .md in docs and link in root readme #202
- [x] Add a readme for LodeRunner #203
- [x] Add a readme for NGSA app #204
- [x] Add a readme for Spikes folder #205
- [x] Let's Encrypt multiple rate limits #175 

## Acceptance Criteria

- Agreed upon document structure 
- Documentation added and peer reviewed

## Constraints
- N/A 

## References:
- References #199

**Comment by dsturgell** [comment]
Need to look at src/ngsa/readme and src/ngsa/test/readme and determine our strategy. Based on the comments of new devs "clicking around", I like having the test details in the test folder and the app details in the app folder with the base folder providing high level info and a "table of contents".

Invest in the readme.md  -- create great dev experience, help others review code

Add things that help people get started:
   - What is it?
   - What it does?
   - Developer roadmap/architecture swimlanes

Should help people easily onboard

**Comment by dsturgell** [comment]
Spikes readme:  

Add a readme to the spikes folder that explains what a spike is and sets expectations for completeness and quality
