### ISSUE TITLE
Engineering Fundamentals Checklist - November

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/ngsa#2]
# Tech Lead's Engineering Fundamentals Checklist

This checklist helps to ensure that our projects meet our Engineering Fundamentals.

## Source Control

- [x] The main branch is locked.
- [x] Merges are done through PRs.
- [x] PRs reference related work items.
- [x] Commit history is consistent and commit messages are informative (what, why).
- [x] Secrets are not part of the commit history or made public. (see [Credential scanning](continuous-integration/credential-scanning/readme.md))
- [x] Public repositories follow the [OSS guidelines](source-control/readme.md#creating-a-new-repository), see `Required files in default branch for public repositories`.

More details on [Source Control](source-control/readme.md)

## Work Item Tracking

- [x] All items are tracked in GitHub
- [x] The board is organized (swim lanes, feature tags, technology tags).

## Testing

- [x] Unit tests cover the majority of all components (>90% if possible).
- [x] Integration tests run to test the solution e2e.

More details on [Unit Testing](automated-testing/unit-testing/readme.md)

## CI/CD

- [x] Project runs CI with automated build and test on each PR.
- [x] Project uses CD to manage deployments to a replica environment before PRs are merged.
- [x] Main branch is always shippable.

## Security 

- [x] Access control.
- [x] Separation of concerns.
- [x] Robust treatment of secrets.
- [x] Encryption for data in transit (and if necessary at rest) and password hashing.

## Observability

- [x] Significant business and functional events are tracked and related metrics collected.
- [x] Application faults and errors are logged.
- [x] Health of the system is monitored.
- [x] The client and server side observability data can be differentiated.
- [x] Logging configuration can be modified without code changes (eg: verbose mode).
- [x] [Incoming tracing context](observability/correlation-id.md) is propagated to allow for production issue debugging purposes.
- [x] GDPR compliance is ensured regarding PII (Personally Identifiable Information).

## Agile/Scrum

- [x] Process Lead (fixed) to run standup daily.
- [x] Agile process clearly defined within team.
- [x] Tech Lead + TPM have responsibility for backlog management and grooming.
- [x] Working agreement between members of team and customer.

## Design Reviews

- [x] Process for conducting design reviews is included in the [Working Agreement](/agile-development/team-agreements/working-agreements/readme.md)
- [x] Design reviews for each major component of the solution are carried out and documented, including alternatives.
- [x] Stories and/or PRs link to the design document.
- [x] Each user story includes a task for design review by default, which is assigned or removed during sprint planning.
- [x] Project advisors are invited to design reviews or asked to give feedback to the design decisions captured in documentation.
- [x] Discover all the reviews that the customer's processes require and plan for them.

## Code Reviews

- [x] Clear agreement in the team as to function of code reviews.
- [x] Code review checklist or established process.
- [x] A minimum number of reviewers (usually 2) for a PR merge is enforced by policy.
- [x] Linters/Code Analyzers, unit tests and successful builds for PR merges are set up.
- [x] Process to enforce a quick review turnaround.

More details on [Code Reviews](code-reviews/README.md)

## Retrospectives

- [x] Set time for retrospectives each week/at the end of each sprint.
- [x] 1-3 proposed experiments to be tried each week/sprint to improve the process.
- [x] Experiments have owners and are added to project backlog.
- [x] Longer retrospective for Milestones and project completion.

More details on [Retrospectives](agile-development/retrospectives/readme.md)

## Engineering Feedback

- [x] Submit business and technical blockers that prevent project success
- [x] Add suggestions for improvements to leveraged services and components
- [x] Ensure feedback is detailed and repeatable

More details on [Engineering Feedback](engineering-feedback/readme.md)
