### ISSUE TITLE
App and Data Service Refactor

### ISSUE THREAD

**Issue by jofultz** [retaildevcrews/ngsa#228]
## Description

What: 
 - Separate the Data Service from the Application
 
Why:
- So that it may be shared by all apps and effect a single reader and single writer paradigm
- Enhancements and optimizations in data access would be received by all consumers instead of building into each app layer

When:
- Development and Deployment

Where:
 - Codebase

## Tasks
- [ ] convert InMemoryDal.cs to use system.text.json #218
- [ ] change app name to dataservice #219
- [ ] change app name to dataservice #219
- [ ] add CVectorBase to log output #220
- [ ] extend CVector to return CVectorBase #221
- [ ] remove trace headers from ds #222
- [ ] remove trace headers from l8r #223
- [ ] remove trace headers from ngsa #224
- [ ] change CVector header to use the default #225
- [ ] Convert CVector to use v2 #226
- [ ] Refactor app components to shared libraries in separate projects #231

## Acceptance Criteria

- Data Service fully independent project
- Common libraries separated into separate projects
- Resolve linter errors
- Remove to-do, dead code, & unnecessary comments
- Existing documentation is updated (readme, .md's)
- New documentation needed to support the change is created
- Validation test run if applicable

## Constraints
- N/A 

## References:
- References #8
