### ISSUE TITLE
Setup BareMetal Pre-Production Environment

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/ngsa#24]
## Description

What: 
 - Setup our pre-production environment including smokers and dashboards.
 - Required Components
   - Smokers
   - IaC Infrastructure setup
   - Dashboards
   - DNS configuration (suggest using ngsa.cse.ms as the end point)
 
Why:
- To deploy the application and monitor the platform

When:
- Continuously

Where:
 - BareMetal

## Tasks
- [x] Deploy infrastructure to BareMetal #33 
- [x] BareMetal Configure dashboard #37
- [x] Deploy application to BareMetal #34
- [x] Add SSL termination to bare metal k8s setup #25 

## Acceptance Criteria

- Infrastructure deployed
- Application deployed
- Smokers Running
- Dashboard setup

## Constraints
- N/A 

## References:
- All related [stories](https://github.com/retaildevcrews/ngsa/projects/2?card_filter_query=label%3ADOPreProd)
- References #16
