### ISSUE TITLE
Complete Initial Documentation 

### ISSUE THREAD

**Issue by jofultz** [retaildevcrews/ngsa#261]
## Description

What: 
 - Complete missing or incomplete documentation
 
Why:
- So that we have a good developer experience 
- So that our solution is reusable

When:
- Ongoing

Where:
 - doc-updates branch until complete

## Tasks
- [x] Complete Observability Section in Iac/AKS/README.md #262
- [x] Complete High Level Architecture Section of ./docs/ApplicationArch.md #263
- [x] Complete ./docs/CICD.md #264
- [x] Complete /IaC/Readme #265
- [x] Complete /NewApp/README.md #267
- [x] Complete /NewApp/ngsa-app/README.md #268
- [x] Update /NewApp/ngsa-typescript #269

## Acceptance Criteria

- Resolve linter errors
- Remove to-do, dead code, & unnecessary comments
- Existing documentation is updated (readme, .md's)
- New documentation needed to support the change is created
- Validation test run if applicable

## Constraints
- N/A 

## References:
- References #199
