### ISSUE TITLE
Migrate to New Environments and Decommission Old

### ISSUE THREAD

**Issue by jofultz** [retaildevcrews/ngsa#355]
# Description

What: 
 
This is to rebuild our environments and consolidate resources in resource groups.  This will establish new clusters and move shared resources.

Note: This may require us to rethink how were naming and using DNS in order to make a graceful switch.
 
Why:
- Test documentation
- Consolidate resources

When:
- ASAP

Where:
 - Azure

## Tasks
- [x] Update alerts with new variables for the new-environment (https://github.com/retaildevcrews/ngsa/issues/342)
- [x] Update dashboard to use new log analytics #372
- [x] Setup GitOps deployments in new environments (https://github.com/retaildevcrews/ngsa/issues/326)
- [x] Transition from `ngsa-temp-log` workspace to `ngsa-pre-log` workspace (https://github.com/retaildevcrews/ngsa/issues/354)
- [x] Switch DNS records to point IP address from old environment to new (https://github.com/retaildevcrews/ngsa/issues/327)
- [x] CosmosDB Setup #367 
- [x] Verify Load testing works on new cluster #350 
- [x] Shutdown old environment (https://github.com/retaildevcrews/ngsa/issues/328)

## Acceptance Criteria

- Replacement cluster in each region
- Names resolve to new clusters
- Loderunner runs successfully against all instances
- Logs are flowing as expected and dashboards are updating

## Constraints
- N/A 

## References:
- Predecessor #181
- Predecessor #171 
- References #10
