### ISSUE TITLE
Setup Pre-prod AKS Cluster

### ISSUE THREAD

**Issue by jofultz** [retaildevcrews/ngsa#43]
## Description

What: 
 - Setup and configure an AKS Pre-production environment
 
Why:
-  So that we may use it for demonstration, testing, and observability

When:
- CI/CD runs or we want to demonstrate current capabilities and metrics

Where:
 - WestUS2

## Tasks
- [x] Review existing scripts and resources and update #71
- [x] Create cluster #59 
- [x] Configure Istio for Service Mesh #60
- [x] Deploy Platform Validation App #61
- [x] Run validation tests against app #62
- [x] Triplet-cluster setup #63
- [ ] Add Helm Variables for application images #112 

## Acceptance Criteria

- Should be able to access the cluster via Kubectl
- Application should be running and accessible via browser
- All validation tests should run
- Documentation should be complete

## Constraints
- N/A 

## References:
- References #16 
- References #47 
- Predecessor #19

**Comment by dsturgell** [comment]
- [ ] Add Helm Variables for application images #112
