### ISSUE TITLE
Investigate, Research, and Design Dashboard Platform

### ISSUE THREAD

**Issue by jofultz** [retaildevcrews/ngsa#44]
## Description

What: 
 - Replicate Helium Dashboard
 - Add metrics to Log Analytics
 - Create dashboard documentation
 - Create dashboard on preprod environment
 
Why:
- To monitor the performance of platform validation app

Where:
 - Azure Dashboards 
 - Log Analytics

## Tasks
- [X] Investigate and Document how relevant metrics are collected #48
- [x] Remove App Insights #93 
- [x] Create dashboard that displays metrics on Helium dashboard #49
- [x] Document setup of required components to run dashboard #52

## Acceptance Criteria

- Design and documentation artifacts added to repo
- Running dashboard for preproduction environment

## Constraints
- N/A 

## References:
- References #12
