### ISSUE TITLE
Sprint 1 Goal - PnP spike, Scaling spike, and Prometheus demo

### ISSUE THREAD

**Issue by atxryan** [retaildevcrews/ngsa#448]
_Put a concise sprint goal here to keep your team focused throughout sprint._

## Commitment

Onboarding
  - [x] `FC:Onboarding` 
  - [x] #407 Record NGSA overview / demo
  - [ ] #444 Update Working Agreement

PnP spike
  - [x] `FC:Pnp`
  - [ ] https://github.com/retaildevcrews/ngsa/issues/383
  - [ ] https://github.com/retaildevcrews/ngsa/issues/178
  - [ ] #318 Design Cluster Monitoring 
 
Scaling Spike
  - [x] `FC:Scaling` 
  - [ ] https://github.com/retaildevcrews/ngsa/issues/411
  - [ ] https://github.com/retaildevcrews/ngsa/issues/416
  - [ ] #434 

### Added to Sprint
_Ensure you list the justification for pulling anything into sprint. Ex: Prod outage, revenue impacts, dev bandwidth, etc._
- add Prometheus / Grafana to standard demo
    - Justification: We will soon have Prometheus metrics for app and LR (driven by WCNP requirement)
    - [x] `FC:Prometheus`
    - [ ] #165 
    - [x] #441 
    - [x] #437
- Fix dead links
    - [x] https://github.com/retaildevcrews/ngsa/issues/445 
    - [x] https://github.com/retaildevcrews/ngsa/issues/365

### Trade-offs
_If you're swapping tickets in, what tickets are falling out?_
- Issue Number

### Feb 15 is a holiday

ACTION: 
- [x] Define schedule
  - [x] Sprints: 1 week, ending on Tuesdays 
- [ ] Schedule Sprint planning sessions
- [x] Schedule NGSA standups for afternoons
