### ISSUE TITLE
Establish baseline CI-CD for Pre-prod environment

### ISSUE THREAD

**Issue by jofultz** [retaildevcrews/ngsa#45]
## Description

What: 
 - CI-CD pipeline that will run for a PR test the application and deploy to the Pre-prod environment
 
Why:
- To increase code quality, ensure the validity of code changes before deployment, and automate deployment

When:
- continuous

Where:
 - GitHub
 - Pre-prod cluster

## Tasks
- [X] Build container 
- [X] Run WebV to validate application
- [ ] Tag and push container to registry - **should this be GitHub registry?**
- [ ] Deploy to Pre-prod environment
- [ ] Run WebV and check results against Pre-prod environment
- [ ] Revert if WebV fails

## Acceptance Criteria

- Image is built and tested
- Image is properly tagged in repo
- Image is deployed to Pre-prod
- Pre-prod deployment is tested
- Pre-prod deployment is reverted if deployment test fails

## Constraints
- N/A 

## References:
- References #

**Comment by jofultz** [comment]
Closing as CI is done and we have a more specific story for CD (#103 ).
