### ISSUE TITLE
Establish Resource Naming Conventions

### ISSUE THREAD

**Issue by jofultz** [retaildevcrews/ngsa#46]
## Description

What: 
 - Establish resource naming conventions 
 
Why:
- Consistency and easy identification of resources and resource group

When:
- continuous

Where:
 - All platforms

## Tasks
- [x] Collect input and create proposal for discussion #69 
- [x] Document as an MD file in /docs #70
- [ ] Setup call with customer to discuss & align to WCNP naming practices
- [ ] Revisit team names in Kubernates namespaces (adhere to WCNP practices) #101

## Acceptance Criteria

- Accepted and documented plan
- Resources updated

## Constraints
- N/A 

## References:
- References #
