### ISSUE TITLE
Setup Shared Dev Cluster

### ISSUE THREAD

**Issue by jofultz** [retaildevcrews/ngsa#47]
## Description

What: 
 - Dev AKS cluster that may be used to deploy and test changes outside of the pre-prod cluster
 
Why:
- Individual user environments may not illuminate all conditions of proper operation for changes. 
- Provide a place to test that will not jeopardize the continuous operation of the Pre-prod environment

When:
- Continuous

Where:
 - West US 2

## Tasks
 - [x] Create cluster #64
 - [x] Configure Istio for Service Mesh #65
 - [x] Deploy Platform Validation App #66
 - [x] Run validation tests against app #67
 - [x] Document Setup #68

## Acceptance Criteria
 - Should be able to access the cluster via Kubectl
 - Application should be running and accessible via browser
 - All validation tests should run
 - Documentation should be complete

## Constraints
- N/A 

## References:
- References #43 
- Reference #16 
- Predecessor #19
