### ISSUE TITLE
Deploy NGSA apps on PnP architecture

### ISSUE THREAD

**Issue by atxryan** [retaildevcrews/ngsa#473]
This is for deploying the NGSA apps on the spike infrastructure.

- deploy PnP architecture as triplets
- deploy and verify ngsa apps
- document any changes needed

More info about aks-secure-baseline. https://github.com/mspnp/aks-secure-baseline

Tasks:

The existing work for the spike is here: https://github.com/retaildevcrews/ngsa/tree/main/spikes/aks-secure-baseline

- [x] Setup Cosmos
- [x] Setup GitOps to deploy ngsa-app on existing AKS cluster from spike walkthrough
- [x] BUG: ngsa-cosmos connection issue.
  - seeing this error in the container logs on startup
  - "The request failed because the client was unable to establish connections to 4 endpoints across 1 regions. Please check for client resource starvation issues and verify connectivity between client and server."
- [x] Setup GitOps to deploy loderunner on existing AKS cluster from spike walkthrough
- [x] Setup GitOps to deploy fluentbit on existing AKS cluster from spike walkthrough (https://github.com/retaildevcrews/ngsa/issues/521)
- [x] Integrate ngsa-secrets and fluentbit-secrets with existing key vault from spike walkthrough. (https://github.com/retaildevcrews/ngsa/issues/529)

Edit: 3/16
Reduced scope of spike to single cluster in aks-secure-baseline-architecture without internet traffic.
- [ ] ~Integrate ngsa-app with Traefik ingress, cse.ms wildcard cert, and key vault (https://github.com/retaildevcrews/ngsa/issues/531)~
- [ ] ~Setup 1 additional network spoke with an AKS cluster (https://github.com/retaildevcrews/ngsa/issues/522)~
- [ ] ~Setup GitOps to deploy ngsa-app to new cluster (https://github.com/retaildevcrews/ngsa/issues/523)~
- [ ] ~Setup GitOps to deploy loderunner to new cluster (https://github.com/retaildevcrews/ngsa/issues/524)~
- [ ] ~Setup GitOps to deploy fluentbit to new cluster (https://github.com/retaildevcrews/ngsa/issues/525)~

**Comment by alkofahi** [comment]
The tasks here are references in https://github.com/retaildevcrews/ngsa/issues/473 for Dynamo to pick up, could you shed some light onto what is blocking this story?

**Comment by AAkindele** [comment]
Reduced scope of spike to single cluster in aks-secure-baseline-architecture without internet traffic.
