### ISSUE TITLE
User Story: Secrets management

### ISSUE THREAD

**Issue by atxryan** [retaildevcrews/ngsa#475]
## Description

What: 
 - Goals
   - Key Rotation
   - Config
   - Spike on Dapr 
      - Validate calls to kv won't be seen as an attack
      - identify which secrets are changing
      - test manage identities to connect dapr resource
      - greenfield/brownfield scenarios
      - test in codespaces
      - check if secret in k8s is changed, what happens with the gitops/sealedsecret operator
 
Why:
- Secret rotation on apps may require the pod to restart
- Security requirements to rotate keys 

When:
- 

Where:
 - 

## Tasks
- [x] Get secrets into AKS from key vault
- [x] Sync secrets in AKS with key vault
- [x] Update workloads with new secrets

## Acceptance Criteria

- [ ] Resolve linter errors
- [ ] Remove to-do, dead code, & unnecessary comments
- [ ] Existing documentation is updated (readme, .md's)
- [ ] New documentation needed to support the change is created
- [ ] Validation test run if applicable

## Constraints
- N/A 

## References:
- References #

**Comment by jsburckhardt** [comment]
Examples:
- direct key vault request through dapr
- direct key vault request if the secret is updated, through dapr
- Inject secret to pod through akv2k8s
- Inject secret to pod through csi
