### ISSUE TITLE
User Story: Monitoring

### ISSUE THREAD

**Issue by atxryan** [retaildevcrews/ngsa#476]
## Description

What: 
 - Goals:
    - Prometheus <> Azure Data Explorer
    - Azure Monitoring & Container Insights
    - more granular app insights / logging
 
Why:
- 

When:
- 

Where:
 - 

## Tasks
- [ ] 

## Acceptance Criteria

- [ ] 
- [ ] Resolve linter errors
- [ ] Remove to-do, dead code, & unnecessary comments
- [ ] Existing documentation is updated (readme, .md's)
- [ ] New documentation needed to support the change is created
- [ ] Validation test run if applicable

## Constraints
- N/A 

## References:
- References #
