### ISSUE TITLE
POC sealed secrets with Flux

### ISSUE THREAD

**Issue by nedruk** [retaildevcrews/ngsa#492]
## Description

What: 
Investigate sealed secrets for the purposes of NGSA project.
 
Why:
Explore sealed secrets as an option for cluster secrets management.
Verify how sealed secrets work with Flux. 

When:
- 

Where:
 - 

## Tasks
- [x] Setup sealed secrets in a cluster running NGSA solution
- [x] Verify how sealed secrets work with Flux
- [ ] How sealed secrets work in multiple clusters scenario 

## Acceptance Criteria

- [ ] 
- [ ] Resolve linter errors
- [ ] Remove to-do, dead code, & unnecessary comments
- [ ] Existing documentation is updated (readme, .md's)
- [ ] New documentation needed to support the change is created
- [ ] Validation test run if applicable

## Constraints
- N/A 

## References:
- References #

**Comment by nedruk** [comment]
## Steps to set up sealed secrets in a cluster running NGSA solution

1. Install sealed secrets in cluster with Helm
```
helm repo add sealed-secrets https://bitnami-labs.github.io/sealed-secrets
helm install sealed-secrets --namespace kube-system --version 1.13.2 sealed-secrets/sealed-secrets
```
2. Install sealed secrets CLI tool 
 
- macos 
```brew install kubeseal```

- linux  
```wget https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.13.1/kubeseal-linux-amd64 -O kubeseal sudo install -m 755 kubeseal /usr/local/bin/kubeseal```
 
13 Create secret manifest, save as secret.aml
```
apiVersion: v1
data:
  CosmosCollection: <CosmosCollection>
  CosmosDatabase: <CosmosDatabase>
  CosmosKey: <CosmosKey>
  CosmosUrl: <CosmosUrl>
kind: Secret
metadata:  
  name: ngsa-secrets
  namespace: ngsa
type: Opaque
```

4. Encrypt ```secret.yaml```, save it as ```sealedsecret.yaml```
```
kubeseal <secret.yaml >sealedsecret.yaml --controller-namespace kube-system --controller-name sealed-secrets --format yaml
```

5. Remove ```secret.yaml```. Push ```sealedsecret.yaml``` to repo that's being monitored by flux.
 
6. A few minutes later when flux sync is done, verify that the new secret is there. 
 
```kubectl get secret ngsa-secrets -o yaml```
