### ISSUE TITLE
Get Kubecon demo running

### ISSUE THREAD

**Issue by sivamu** [retaildevcrews/ngsa#5]
## Description

What: 
 - Update the Kubecon demo

Why:
- to align to NGSA cloud native work

When:
- as soon as possible

Where:
 - in code and documentation

## Tasks
- [X] API features for kubecon demo https://github.com/retaildevcrews/helium/issues/30
- [X] Kubecon Demo-in-a-Box https://github.com/retaildevcrews/helium/issues/41
- [X] Retro: Post KubeCon - capture feedback for improvements https://github.com/retaildevcrews/helium/issues/49
- [ ] Add Log Analytics Workspace to Kubecon Demo Setup https://github.com/retaildevcrews/helium/issues/623
- [ ] Add Fluentbit to Kubecon Deployment  https://github.com/retaildevcrews/helium/issues/624
- [ ] Add Log Analytics Based Dashboard Components https://github.com/retaildevcrews/helium/issues/625

## Acceptance Criteria

- usable walkthru
- running demo at end of walkthru
- complete dashboards

## Constraints
- N/A 

## References:
- References #148

**Comment by jofultz** [comment]
BLOCKED due to the observability aspect not decided.
