### ISSUE TITLE
Sprint 2 tracking

### ISSUE THREAD

**Issue by atxryan** [retaildevcrews/ngsa#501]
### 👩🏾‍💻👩🏻‍💻 POINT DEV 👩🏻‍💻 👩🏾‍💻
- Kushal & Gerardo

### Sprint tracking 
PnP spike
  - [x] `FC:Pnp`
  - [x] [Delta: aks-secure-baseline <> NGSA](https://github.com/retaildevcrews/ngsa/issues/178)
  - [x] [Design Cluster Monitoring](https://github.com/retaildevcrews/ngsa/issues/318) 
  - [ ] [Deploy NGSA apps on PnP architecture](https://github.com/retaildevcrews/ngsa/issues/473)
  - [ ] [infrastructure update checklist #433](https://github.com/retaildevcrews/ngsa/issues/433)
  - [x] [AKS Secure Baseline Design Review #461](https://github.com/retaildevcrews/ngsa/issues/461)

 
Scaling Spike
  - [x] `FC:Scaling` 
  - [ ] https://github.com/retaildevcrews/ngsa/issues/411
  - [ ] https://github.com/retaildevcrews/ngsa/issues/416
  - [x] [Loderunner 503s](https://github.com/retaildevcrews/ngsa/issues/434)

GitOps & Arc
  - [x] `FC:GitOps-Arc` 
  - [ ] [GitOps & Arc](https://github.com/retaildevcrews/ngsa/issues/478) 
  - [ ] [POC Arc for NGSA](https://github.com/retaildevcrews/ngsa/issues/493)
  - [ ] [POC sealed secrets with Flux](https://github.com/retaildevcrews/ngsa/issues/492)

AKDC
 - [x] `FC:akdc`
 - [ ] [akdc template #6](https://github.com/retaildevcrews/akdc-kind/issues/6)
 - [x] [add docs on helm #29](https://github.com/retaildevcrews/akdc-kind/issues/29)
 - [ ] [codespaces - permissioned denied #16](https://github.com/retaildevcrews/akdc-kind/issues/16)
 - [ ] [workspace issues #20](https://github.com/retaildevcrews/akdc-kind/issues/20)

Secrets mgmt
- [x] `FC:SecretsMgmt`
- [ ] [User Story: Secrets management #475](https://github.com/retaildevcrews/ngsa/issues/475)

 Sharing & Docs
 - [ ] [publish akdc-kind #28](https://github.com/retaildevcrews/akdc-kind/issues/28)
 - [x] [update k8s-quickstart content #465](https://github.com/retaildevcrews/ngsa/issues/465)
 - [ ] [Sharing: Kubernetes components (03/02) #470](https://github.com/retaildevcrews/ngsa/issues/470)
 - [ ] [Sharing: Walkthrough of NGSA project boards, repos, and processes. (3/1) #503](https://github.com/retaildevcrews/ngsa/issues/503)
 - [x] [Update repo docs and YAML to use ghcr.io #471](https://github.com/retaildevcrews/ngsa/issues/471)
 - [ ] [infrastructure update checklist #433](https://github.com/retaildevcrews/ngsa/issues/433)
 - [x] [Update AKS Readme: use charts in ./gitops, since `ngsa-cd` repo is removed #496](https://github.com/retaildevcrews/ngsa/issues/496)

### Sprint Adjustments
  - [ ] Update SSH encryption https://github.com/retaildevcrews/ngsa/issues/489 
    - Justification: Security alert
  - [x] Remove  [Create a private network](https://github.com/retaildevcrews/ngsa/issues/383) from Sprint
    - Wait on PnP baseline to be setup
  - [ ] Added [ci-cd - docker push #304](https://github.com/retaildevcrews/ngsa/issues/304)
    - Build agents are now using new CLI

### Notes
- Redback Crew joins Sprint Febuary 16th
