### ISSUE TITLE
Sprint 3 Tracking

### ISSUE THREAD

**Issue by atxryan** [retaildevcrews/ngsa#527]
### 👩🏾‍💻👩🏻‍💻 POINT DEV 👩🏻‍💻 👩🏾‍💻
- FC: GitOps-Arc

### Sprint tracking 
PnP spike
  - [x] `FC:Pnp`
  - [ ] [Deploy NGSA apps on PnP architecture](https://github.com/retaildevcrews/ngsa/issues/473)
  - [ ] [infrastructure update checklist #433](https://github.com/retaildevcrews/ngsa/issues/433)
 
Scaling Spike
  - [x] `FC:Scaling` 
  - [ ] https://github.com/retaildevcrews/ngsa/issues/411
  - [ ] https://github.com/retaildevcrews/ngsa/issues/416

GitOps & Arc
  - [x] `FC:GitOps-Arc` 
  - [x] [GitOps & Arc](https://github.com/retaildevcrews/ngsa/issues/478) 
  - [ ] [POC Arc for NGSA](https://github.com/retaildevcrews/ngsa/issues/493)
  - [x] [POC sealed secrets with Flux](https://github.com/retaildevcrews/ngsa/issues/492)

AKDC
 - [x] `FC:akdc`
 - [ ] [akdc template #6](https://github.com/retaildevcrews/akdc-kind/issues/6)
 - [x] [codespaces - permissioned denied #16](https://github.com/retaildevcrews/akdc-kind/issues/16)
 - [x] [workspace issues #20](https://github.com/retaildevcrews/akdc-kind/issues/20)

Secrets mgmt
- [x] `FC:SecretsMgmt`
- [ ] [User Story: Secrets management #475](https://github.com/retaildevcrews/ngsa/issues/475)

 Sharing & Docs

### Sprint Adjustments
  - [ ] Update SSH encryption https://github.com/retaildevcrews/ngsa/issues/489 
    - Justification: Security alert
  - [x] Remove  [Create a private network](https://github.com/retaildevcrews/ngsa/issues/383) from Sprint
    - Wait on PnP baseline to be setup
  - [ ] Added [ci-cd - docker push #304](https://github.com/retaildevcrews/ngsa/issues/304)
    - Build agents are now using new CLI
 - Removed [publish akdc-kind #28](https://github.com/retaildevcrews/akdc-kind/issues/28)
 - Removed [Sharing: Walkthrough of NGSA project boards, repos, and processes. (3/1) #503](https://github.com/retaildevcrews/ngsa/issues/503)

### Notes
- Dynamo Crew joins Sprint 3/3
