### ISSUE TITLE
Sprint 4 tracking

### ISSUE THREAD

**Issue by atxryan** [retaildevcrews/ngsa#553]
## Sprint Goal
_Deploy NGSA to aks-secure-baseline pattern. Identify monitoring features to implement from spikes._

### 👩🏾‍💻👩🏻‍💻 POINT DEV 👩🏻‍💻 👩🏾‍💻
- ???

### Sprint tracking 
`FC:PnP-Deploy`
  - [ ] [Deploy NGSA apps on PnP architecture](https://github.com/retaildevcrews/ngsa/issues/473)
  - [x] [Integrate ngsa and fluentbit secrets with existing key vault from spike walkthrough #529]
  - [ ] [infrastructure update checklist #433](https://github.com/retaildevcrews/ngsa/issues/433)
  - [ ] [Integrate ngsa-app with Traefik ingress, cse.ms wildcard cert, and key vault #531]
  - [ ] [filter web traffic #349]
  - [ ] [Create 1 additional network spokes on aks-secure-baseline #522]
    - [ ] [Deploy ngsa-app to additional cluster on aks-secure-baseline #523]
    - [ ] [Deploy loderunner to additional cluster on aks-secure-baseline #524]
    - [ ] [Deploy fluentbit to additional cluster on aks-secure-baseline #525]

`FC:Monitoring` 
  - [x] 

 Sharing & Docs
 - [ ] [Sharing: Walkthrough of NGSA project boards, repos, and processes. (3/1) #503](https://github.com/retaildevcrews/ngsa/issues/503)

### Sprint Adjustments
  - [ ] Update SSH encryption https://github.com/retaildevcrews/ngsa/issues/489 
    - Justification: Security alert

### Notes

**Comment by chkinney** [comment]
Should this be tagged with `FC:PnP-deploy`?
