### ISSUE TITLE
Secure Baseline Upskilling

### ISSUE THREAD

**Issue by Natasha-Kohli** [retaildevcrews/ngsa#560]
## Description

What: 
Upskilling on kubernetes and the secure baseline infrastructure.
 
Why:

When:

Where:
 

## Tasks
- [x] Read through [baseline architecture documentation](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks/secure-baseline-aks)
- [x] Watch baseline architecture [video](https://msit.microsoftstream.com/video/ed03a4ff-0400-96f3-562d-f1eaee137cf3)
- [x] Kubernetes on [pluralsight](https://app.pluralsight.com/library/courses/kubernetes-getting-started/table-of-contents)

## Constraints
- N/A 

## References:
- References #
