### ISSUE TITLE
Default setup of aks-secure-baseline with NGSA 

### ISSUE THREAD

**Issue by AAkindele** [retaildevcrews/ngsa#588]
## Description

What: 
 - Evaluate the terraform implementation for aks-secure-baseline from the Microsoft cloud adoption framework(CAF)
 - Customized version of the aks-secure-baseline setup (NGSA/LodeRunner)
 
Why:
- Repeatable deployment of the NGSA version of aks-secure-baseline 

Where:
 - RetailDevCrews GH
 
## Tasks
- [x] Evaluate terraform implementation of aks-secure-baseline from CAF  https://github.com/retaildevcrews/ngsa/issues/618
- [x] remote terraform state  https://github.com/retaildevcrews/ngsa/issues/611
- [x] create scripting for terraform setup  https://github.com/retaildevcrews/ngsa/issues/612
- [x] scripting integration with aks-secure-baseline https://github.com/retaildevcrews/ngsa/issues/630
- [x] customize resources for NGSA  https://github.com/retaildevcrews/ngsa/issues/614

## Acceptance Criteria
- Deploy a NGSA customized version of aks-secure-baseline infrastructure

## Constraints
- 

## References:
- References #10

**Comment by chenmliu** [comment]
**Suggestions:**
1. Change the deployment region to the one closest to you for better latency. Update the "region1" variable in the following file to other acceptable regions, e.g., eastus:
..\enterprise_scale\construction_sets\aks\online\aks_secure_baseline\configuration\global_settings.tfvars
2. Prefix all the resource groups names with a unique string to easy filtering. Prefix all the "name" variables in the following file with an unique string, e.g., demo:
..\enterprise_scale\construction_sets\aks\online\aks_secure_baseline\configuration\global_settings.tfvars
3. To have the script create an AAD group and have it added as the cluster admin,
(1) Rename replace "ignore" with "tfvars" for the following file:
 ..\enterprise_scale\construction_sets\aks\online\aks_secure_baseline\configuration\iam\iam_aad.ignore
(2) Uncomment the following lines in the role_based_access_control in the following file:
..\enterprise_scale\construction_sets\aks\online\aks_secure_baseline\configuration\aks.tfvars
```
        admin_group_object_ids = ["7304e4e7-b148-4ada-a135-6049c702d21e"]
        azuread_groups = {
          keys = ["aks_cluster_re1_admins"]
        }
```

**Observations:**
1. When you run the script, an unique 4-character string is all the resource groups names for easy filtering. So the script can be run against the same subscription multiple times without cause name conflict.
 
**Troubleshooting cluster admin not set issue**
If you run the script from the CAF (Cloud Adoption Framework) repo (https://github.com/Azure/caf-terraform-landingzones-starter/tree/starter/enterprise_scale/construction_sets/aks/online/aks_secure_baseline) as is, by default the code/file to create a AAD user group and add it as cluster admin is commented out. And you'll run into issue at step 6 in this doc (https://github.com/Azure/caf-terraform-landingzones-starter/blob/starter/enterprise_scale/construction_sets/aks/online/aks_secure_baseline/02-aks.md). When you run kubectl get pods -n a0008, you will see neither of the two traefik ingress controllers are running (i.e., both have status 0/1). When you open the application url from the browser, you'll see a "502 Bad Gateway" error message.
 
A temporary walkaround:
1. On the Azure portal, open the Kubernetes service created by Terraform, click 'Cluster configuration' in the middle menu, you will see "Admin Azure AD groups" not set. Click the edit button, and search for "PnP Deploy" in the list, and save the change. 
2. Repeat the steps starting from step 4. In step 6, verify that both traefik ingress controllers are up and running. https://github.com/Azure/caf-terraform-landingzones-starter/blob/starter/enterprise_scale/construction_sets/aks/online/aks_secure_baseline/02-aks.md
 
A long-term solution:
1. Update the aks Terraform file to set the "PnP Deploy" AAD group as the cluster admin by including its ID and name in the role_based_access_control.admin_group_object_ids and role_based_access_control.azuread_groups, respectively
2. Further improvement - parameterize these two values in either one of the existing tfvars files (e.g. global_settings.tfvars) or create a AAD specific tfvars file, so it's easy to customize/update these values in a separate file.
 
Other notes: 
 
https://github.com/Azure/caf-terraform-landingzones-starter/blob/starter/enterprise_scale/construction_sets/aks/online/aks_secure_baseline/02-aks.md
 
When running `kubectl get pods -n a0008`, make sure both traefik ingress controllers is running. Expected output:

```
NAME                                          READY   STATUS    RESTARTS   AGE
aspnetapp-deployment-7ccf7cb7f9-6ltsd         1/1     Running   0          61s
aspnetapp-deployment-7ccf7cb7f9-wh2lp         1/1     Running   0          61s
traefik-ingress-controller-844fcdd859-k7dgj   0/1     Running   0          58s
traefik-ingress-controller-844fcdd859-p6g8w   0/1     Running   0          58s
```
