### ISSUE TITLE
NGSA DevX - Sprint 4 Retro

### ISSUE THREAD

**Issue by atxryan** [retaildevcrews/ngsa#591]
### Link
https://rdc-retro.azurewebsites.net/game/IAJUsiVLf

### Tasks

- [ ] Add Retro summary into Issue
- [ ] Create issues for relevant action items
- [x] If final sprint for milestone. create milestone summary to share
