### ISSUE TITLE
Address annotations security issues from SPIKE

### ISSUE THREAD

**Issue by atxryan** [retaildevcrews/ngsa#602]
## Description

What: 
 - Implement an HTTPS API endpoint to post annotations
 - Address security issues from #463 Graphana annotations spike  (PR #538)
 
Why:
- Grafana has a feature for adding annotations to charts. We want to do this in an annotated way.
For example, when a load test starts, we want to add an annotation to the grafana charts.

When:
- ASAP

Where:
 - 

## Tasks
- [ ] #438 

## Acceptance Criteria

- [ ] 
- [ ] Resolve linter errors
- [ ] Remove to-do, dead code, & unnecessary comments
- [ ] Existing documentation is updated (readme, .md's)
- [ ] New documentation needed to support the change is created
- [ ] Validation test run if applicable

## Constraints
- Coordinate with `PnP-Deploy` on cert #531

## References:
- References #

**Comment by chkinney** [comment]
- Enable HTTPS endpoint for Grafana to enable secure connection from outside the cluster to Grafana inside the cluster.
- Not a goal in this task to enable HTTPS between services within the cluster.

**Comment by chkinney** [comment]
Check with AK on status of using Traefik and HTTPS

**Comment by chkinney** [comment]
For now, use self-signed certs and use `kubectl port-forward` to expose an endpoint locally. Grafana has some configs ([1](https://grafana.com/docs/grafana/latest/administration/configuration/#protocol), [2](https://grafana.com/docs/grafana/latest/administration/configuration/#cert_file)) that can be used to listen on HTTPS.
