### ISSUE TITLE
Integrate Load Tests into Graphana annotationl API

### ISSUE THREAD

**Issue by atxryan** [retaildevcrews/ngsa#605]
## Description

What: 
 - 
 
Why:
- 

When:
- 

Where:
 - 

## Tasks
- [ ] Design Review

## Acceptance Criteria

- [ ] 
- [ ] Resolve linter errors
- [ ] Remove to-do, dead code, & unnecessary comments
- [ ] Existing documentation is updated (readme, .md's)
- [ ] New documentation needed to support the change is created
- [ ] Validation test run if applicable

## Constraints
- Depends on #602 before implementation

## References:
- References #602
