### ISSUE TITLE
DEV: Install ngsa-inmemory

### ISSUE THREAD

**Issue by atxryan** [retaildevcrews/ngsa#607]
## Description

What: 
 - Do we have a way to automate the config?
 - Install ngsa-app, ngsa-inmemory, ngsa-cosmos
   - Refer to the `pnp-deploy` ingress controller
 - What is the terraform delta to enable OMS?
 
Why:
- 

When:
- 

Where:
 - 

## Tasks
- [ ] 

## Acceptance Criteria

- [ ] 
- [ ] Resolve linter errors
- [ ] Remove to-do, dead code, & unnecessary comments
- [ ] Existing documentation is updated (readme, .md's)
- [ ] New documentation needed to support the change is created
- [ ] Validation test run if applicable

## Constraints
- N/A 

## References:
- References #511

**Comment by jomalsan** [comment]
I believe that this task has been replaced by #628 and can be closed.

CC: @atxryan, @jkeane

**Comment by jomalsan** [comment]
@PurpleBriar and I connected on this topic and are going to research what has been deployed today and will work on splitting out the tasks in Standup on Wednesday, once we have a bit more context

**Comment by jomalsan** [comment]
CAF Terraform can be found here: https://github.com/retaildevcrews/caf-terraform-landingzones-starter
And the post aks install instructions are: https://github.com/retaildevcrews/caf-terraform-landingzones-starter/blob/main/enterprise_scale/construction_sets/aks/online/aks_secure_baseline/02-aks.md
