### ISSUE TITLE
Monitoring Sprint 2 (3/23-3/30)

### ISSUE THREAD

**Issue by jkeane** [retaildevcrews/ngsa#608]
Dashboard Annotations
- [x] #602 Address annotations security issues from SPIKE
- [ ] #605 Load Test Integration of Annotations
    * Feature Design
    * Feature Implementation

OMS Agent Integration for App Metrics
- [x] #511 Feature Design review
- [ ] #607 Feature Implementation
- [ ] #606 Publish PnP Guidance (documentation? IaC?)

Next Phase Designs
- [ ] Personas
- [ ] Single Instance
- [ ] (Plan of Features)
