### ISSUE TITLE
Monitoring Sprint 3

### ISSUE THREAD

**Issue by atxryan** [retaildevcrews/ngsa#638]
## Sprint Goal
_Put a concise sprint goal here to keep your team focused throughout sprint._

## Commitment
Dashboard Annotations
- [x] #602 Address annotations security issues from SPIKE
- [ ] #605 Load Test Integration of Annotations
    * Feature Design
    * Feature Implementation

OMS Agent Integration for App Metrics
- [x] #511 Feature Design review
- [ ] #607 Feature Implementation
- [ ] #606 Publish PnP Guidance (documentation? IaC?)

Next Phase Designs
- [ ] Personas
- [ ] Single Instance
- [ ] (Plan of Features)

### Added to Sprint
_Ensure you list the justification for pulling anything into sprint. Ex: Prod outage, revenue impacts, dev bandwidth, etc._
- [ ] # (issue number)
    - **Justification:**

### Trade-offs
_If you're swapping tickets in, what tickets are falling out?_
- Issue Number
