### ISSUE TITLE
Add private Azure Container Registry to default infrastructure setup

### ISSUE THREAD

**Issue by AAkindele** [retaildevcrews/ngsa#652]
## Description

What: 
 - Add a private Azure Container Registry to the setup of the infrastructure
 
Why:
- Align with guidance from Patterns and Practices [aks-secure-baseline](https://github.com/mspnp/aks-secure-baseline)
- This is currently missing from the default CAF terraform implementation of aks-secure-baseline that we are using

When:
- On environment creation

Where:
 - aks-secure-baseline infrastructure

## Tasks
- [ ] Document the components and configuration of the private ACR from aks-secure-baseline
- [ ] Create ACR to match specs from aks-secure-baseline (https://github.com/retaildevcrews/ngsa/issues/644)
- [ ] Design review for keeping public, non-NGSA, images in sync with ACR
- [ ] Design review for updates to NGSA build process and ACR integration
- [ ] Implement process for keeping public, Non-NGSA, images in sync with ACR
- [ ] Integrate NGSA build process and ACR
- [ ] Update all images in cluster to use private ACR

## Acceptance Criteria
- ACR configuration matches what is created from https://github.com/mspnp/aks-secure-baseline/blob/main/cluster-stamp.json
- All images in the cluster are coming from ACR

## Constraints
- Can this be done by using the [CAF terraform module](https://github.com/aztfmod/terraform-azurerm-caf)?

## References:
- References #
