### ISSUE TITLE
Sprint 3 retro

### ISSUE THREAD

**Issue by atxryan** [retaildevcrews/ngsa#660]
## NGSA DevX Retro - Sprint 3

# Retrospected Session

### Session details:

**Date**: Wednesday, 7 April 2021 at 11:57:13 GMT-05:00

**URL**: https://rdc-retro.azurewebsites.net/game/HLm-1gG1r

**Participants**: Chenmin, Chris K, Jafar, Jon, Kevin, Kushal, Nsikan, Ryan, aakindele, bartr, deanna, jk, natasha, siva

**Posts**: 28

**Votes**: 65

### Actions

- - Add language to onboarding / working agreement about "how" we use Teams chats
- Experiment w/ onboarding channel for next Crew

#### Start

- (+5/-0) Empowering team to create notes/issues for new work uncovered
- (+2/-0) Capturing action items on the board for things that are discovered during the sprint
- (+1/-0) Capture/label discussion topics or potential collision points across both boards
- (+0/-0) Help Ryan's Internet

  
#### Continue

- (+12/-0) Ad-hoc sync to help unblock each other
- (+8/-0) Using the shared chat for video calls to discuss amongst the team
- (+6/-0) revisiting the sprint goals in standup
- (+5/-0) Discussing issues that we run into across Feature Crews
- (+3/-0) pairing across Feature Crews on common infra tasks
- (+2/-0) Conversations around scope and breaking down tasks
- (+2/-0) Review PRs
- (+2/-0) **Onboarding**  
    	- (+2/-0) Providing feedback for "Combining Crew" retro 
- (+1/-0) Sharing learnings and tools with other crews
- (+0/-0) As devs, ignoring the shared NGSA board and focusing only on the Feature Crew boards

  
#### Fave thing to cook?

- (+2/-0) cookies!
- (+2/-0) Still Austin Sherry Cask Rye Manhattan
- (+2/-0) Biriyani
- (+1/-0) mini pizzas
- (+1/-0) bacon-wrapped chicken (currently)
- (+1/-0) venison chili
- (+1/-0) Poke
- (+1/-0) Tofu and green bean curry
- (+1/-0) Spaghetti
- (+1/-0) Italian Meringue Pastries
- (+1/-0) experiment with steak seasoning
- (+1/-0) red curry beef
- (+1/-0) Portuguese egg cake
- (+0/-0) anything sous vide

### Tasks

- [x] Add Retro summary into Issue
- [ ] Create issues for relevant action items
- [ ] If final sprint for milestone. create milestone summary to share
