### ISSUE TITLE
Investigate "break glass" AKS admin Active Directory Security Group and User

### ISSUE THREAD

**Issue by Natasha-Kohli** [retaildevcrews/ngsa#669]
## Description

Based off of the work done in [issue 630](https://github.com/retaildevcrews/ngsa/issues/630), the provision environment bash script was integrated with the CAF terraform scripts with the necessary permissions needed to deploy all the CAF resources. The [CAF ReadME](https://github.com/retaildevcrews/caf-terraform-landingzones-starter/tree/main/enterprise_scale/construction_sets/aks/online/aks_secure_baseline) mentions that the Azure AD User Administrator is required to create a "break glass" AKS admin Active Directory Security Group and User, but giving the service principal this Azure AD role will require admin approval.
Investigate the pros and cons between granting admin consent to the Microsoft Graph permissions in _prepare_terraform script (a workaround for the User Administrator role, see the [terraform documentation](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/guides/service_principal_configuration#method-2-api-access-with-admin-consent) for details), or not automating the "break glass" admin step within the terraform deployment.

## Tasks
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 

## Acceptance Criteria

- [ ] Design document on the best approach, keeping deployment and CI/CD in mind
- [ ] Resolve linter errors
- [ ] Remove to-do, dead code, & unnecessary comments
- [ ] Existing documentation is updated (readme, .md's)
- [ ] New documentation needed to support the change is created
- [ ] Validation test run if applicable

## Constraints
- N/A 

## References:
- References #
