### ISSUE TITLE
Infrastructure end-to-end bug investigation and fixes

### ISSUE THREAD

**Issue by AAkindele** [retaildevcrews/ngsa#701]
## Description

What: 
 - Investigate and/or fix issues discovered during the [end-to-end validation](https://github.com/retaildevcrews/ngsa/issues/667) of infrastructure setup
 
Why:
- Improve quality of documentation
- Improve dev experience

Where:
 - Infrastructure setup documentation

## Tasks
- [x] Document directory from where to run commands https://github.com/retaildevcrews/ngsa/issues/703
- [x] Is terraform service principal being used? https://github.com/retaildevcrews/ngsa/issues/702
- [x] Missing prefix in key vault name https://github.com/retaildevcrews/ngsa/issues/678

## Acceptance Criteria
- Issues identified here are either resolved or investigated with proposed next steps

## Constraints
- N/A 

## References:
- References https://github.com/retaildevcrews/ngsa/issues/667
