### ISSUE TITLE
Terraform setup bug investigation and fixes

### ISSUE THREAD

**Issue by AAkindele** [retaildevcrews/ngsa#708]
## Description

What: 
 - Investigate and/or fix issues related to the terraform provisioning script that was discovered during the [end-to-end validation](https://github.com/retaildevcrews/ngsa/issues/667) of the infrastructure setup.
 
Why:
- Fix known issues in provisioning script

When:
- Setup required to run terraform

Where:
 - terraform provisioning script and documentation

## Tasks
- [x] Investigate generated terraform.tfvars file https://github.com/retaildevcrews/ngsa/issues/704
- [x] Improve experience of using the provisioning script multiple times https://github.com/retaildevcrews/ngsa/issues/709
- [x] Formatting issue with double quotes in terraform.tfvars https://github.com/retaildevcrews/ngsa/issues/705

## Acceptance Criteria
- Issues identified here are either resolved or investigated with proposed next steps

## Constraints
- N/A 

## References:
- References #
