### ISSUE TITLE
NGSA - Retro - M1 - Sprint1

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/ngsa#83]
### Summary

**Date**: Tuesday, 10 November 2020 at 14:32:57 GMT-06:00

#### Liked

- (+13/-0) The collaboration of the team - a great group to work with!
- (+9/-0) We have logs flowing and have already gathered some insights and have some hypothesis.
- (+7/-0) Being able to leverage a lot of the NGSA work for a successful One Week project
- (+7/-0) Seeing impromptu collab meetings popping up
- (+5/-0) Lots of progress across all epics. Very impactful sprint.

#### Learned

- (+6/-0) The importance of having kubernetes aliases for common tasks :)
- (+5/-0) A lot more about Log Analytics
- (+5/-0) Multipass :)
- (+4/-0) A bit about DestinationRules, subsets, routes, virtualservices, etc.
- (+3/-0) How to build and deploy a sidecar.
- (+3/-0) Got to learn about Istio and how some of the components work. Also learned that there is A LOT more to learn about Istio and service meshes!
- (+3/-0) Grafana dashboard with Azure Monitor
- (+2/-0) Power BI has a new look/layout and moved things around, but lost some features
- (+2/-0) Learned how to use credscan. Shout out to Bart for walkthrough.
- (+2/-0) Learned that resource groups can have resources in different locations.
- (+2/-0) SSL/TLS certs, enabling Https for a web service and cert manager
- (+0/-0) Learned that you can have k8s health probes for non http services
  
#### Lacked

- (+4/-0) More time for One "Week"
  
#### Longed For

- (+6/-0) Turf and surf; 2nd Bar; Lonesome Dove; Cooper's; Taco Deli; SPiN - WITH the team :(
- (+0/-3) ^- Does this mean someone went to SPIN without the team? 😮
  
#### Thanks to/for

- (+7/-0) The whole team for jumping in on short notice repeatedly to unblock teammates.
- (+5/-0) Anne for her pirate skills and creating a picture that showed exactly what I was trying to say.  aRRRRRRRRRRRRRRRRR
- (+5/-0) Kevin joining the team
- (+4/-0) A lot of pairing/group sessions with the team.
- (+1/-0) Bart for great documentation in the BM setup, made it very easy to mirror functionality in AKS setup

### Tasks

- [X] Add Retro summary into Issue
- [ ] Create issues for relevant action items
- [ ] If final sprint for milestone. create milestone summary to share
