### ISSUE TITLE
Configure git for consistent line endings based on OS

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/ngsa#89]
## Description

What: 
 - consistently for line endings across development environment operating systems
 
Why:
- so changes show up properly in PRs and commits

When:
- as items are committed to the repo

Where:
 - github and dev machines

## Tasks
- [ ] Update working agreement
- [ ] Add gitconfig to repo

## Acceptance Criteria
- [ ] expected line endings (lf)

## Constraints
- N/A 

## References:
- References #11

**Comment by dsturgell** [comment]
here is a starting point for discussion

> autocrlf = true should only be used on Windows

Each dev runs:

```
git config --global core.whitespace blank-at-eol,blank-at-eof,space-before-tab
git config --global core.autocrlf true

git config --global pull.rebase false
git config --global init.defaultbranch main

git config --global user.name your_user_name
git config --global user.email your_user_name@microsoft.com
```

Each repo contains in .git/config (I think)

```
[core]
  whitespace = blank-at-eol,blank-at-eof,space-before-tab
[pull]
        rebase = false
[init]
        defaultBranch = main
```

We should probably also add a .gitattributes where .sh line endings are always lf as they won't run otherwise. Just in case someone tries to check in a CRLF in a .sh file.
