### ISSUE TITLE
Add credential scan in github actions

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/ngsa#91]
## Description

What: 
 - Cred Scanning as part of PR workflow
 
Why:
- so that secrets will be merged into main branch

When:
- PR submitted, timer (1/week)

Where:
 - GitHub

## Tasks
- [ ] Design mechanism to store/run tool (custom container)
- [ ] Github workflow integration
- [ ] Documentation for scan execution and issue remediation steps
- [ ] Create schedule job
 
## Acceptance Criteria
- Cred Scan will run as part of workflow
- Catches secrets and credentials
- Documented user process for remediation

## Constraints
- Must use internal scanning tool

## References:
- References #11

**Comment by dsturgell** [comment]
Since the cred tool is not public hence, we can integrate it into pipeline in 2 ways:
  - Azure ACR
  - Azure Storage

@bartr  - we could also use a private docker hub repo or a private github repo since we already have the credentials and the docker hub login

- Recommend dev to add git pre-push-hook to run cred scan. In this way it can be made sure that devs don't push cred into github

**Comment by dsturgell** [comment]
Enabled by GitHub; no longer needed
